# Gitlab CI file
# Includes four stages: install, lint, test, build.
# First job is manual by design, 
# thus ensuring that the CI is not triggered automatically.
# Test Engineer triggers CI before merging to main branch.
default:
  image: node:latest
  before_script:
    - export PATH="/home/system/.nvm/versions/node/v20.20.2/bin:$PATH"

stages:
  - lint
  - test
  - build

lint-and-install:
  when: manual
  stage: lint
  script:
    - cd apps/web && npm ci && npm run lint

unit-tests:
  stage: test
  needs: [lint]
  script:
    - cd apps/web && npm ci && npx vitest run tests/unit --reporter=default --reporter=junit --outputFile=unit-test-results.xml
  artifacts:
    when: always
    reports:
      junit: apps/web/unit-test-results.xml

contract-tests:
  stage: test
  needs: [lint]
  script:
    - cd apps/web && npm ci && npx vitest run tests/contract --reporter=default --reporter=junit --outputFile=contract-test-results.xml
  artifacts:
    when: always
    reports:
      junit: apps/web/contract-test-results.xml

build:
  stage: build
  needs: [unit-tests, contract-tests]
  script:
    - cd apps/web && npm ci && npm run build
  artifacts:
    paths:
      - apps/web/dist/
    expire_in: 1 week
